### ISSUE TITLE
Cluster example doesn't work

### ISSUE THREAD

**Issue by janekolszak** [rroemhild/docker-ejabberd#100]
Hi,
I went through the example/docker-compose-cluster. Had to change docker-compose.yml
- Changed domainname to localhost
- Changed dns address
- EJABBERD_ADMINS, EJABBERD_USERS are on localhost

So it's:
```
dnsdock:
  image: tonistiigi/dnsdock
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - 172.17.0.1:53:53/udp

ejabberd:
  build: .
  ports:
    - 5222
    - 5269
    - 5280
  environment:
    - XMPP_DOMAIN=localhost
    - ERLANG_NODE=ejabberd
    - EJABBERD_ADMINS=admin@localhost
    - EJABBERD_USERS=admin@localhost:test321 user@localhost
    - ERLANG_COOKIE=testCluster
    - SKIP_MODULES_UPDATE=true
    - EJABBERD_CLUSTER=true
    - USE_DNS=true
  dns: 172.17.0.1
  domainname: localhost
  tty: true
```

When I scale up ejabberd new instances are created but not connected in a cluster. 

After I connect to the master's http gui I can't see the other nodes.
What could be the  problem?

Thanks!
