### ISSUE TITLE
Specify custom cert-paths per domain with inofity-option

### ISSUE THREAD

**Issue by MaZderMind** [rroemhild/docker-ejabberd#140]
My Certificates com from an acme-pod which fetches the certificates from the Let's encrypt CA.
They are stored as files in a volume which can be mounted into various containers needing them, but the exact filenames and directory structure is given.

To use them with this ejabberd-image it would be necessary to add another pre-script which takes the in-container path of a certificate for each domain (and the host-cert) and copies them to the .pem-file locations required by the startup procedure.

Furthermore, most cert sources do not naturally produce the combined format (priv-key ü cert + intermediate) required by ejabberd, so it would be necessary to specify multiple files which would be joined by the startup-script.

For example such a config would match the current scheme:
```
env:
- name: EJABBERD_SSLCERT_HOST_PATH
  value: '/var/certs/mazdermind.de/fullchain /var/certs/mazdermind.de/privkey'

- name: EJABBERD_SSLCERT_EXAMPLE_DE_PATH
  value: '/var/certs/example.de/fullchain /var/certs/example.de/privkey'

- name: EJABBERD_SSLCERT_EXAMPLE_ORG_PATH
  value: '/var/certs/example.org/fullchain /var/certs/example.org/privkey'
```
