### ISSUE TITLE
Container only stays up for 1 minute

### ISSUE THREAD

**Issue by scallopedllama** [rroemhild/docker-ejabberd#148]
I've been trying to use this container to run Ejabberd but have only managed to get it to keep the container up for about 1 minute. After that, the container exits 0 with no indication as to why. 

Running the example from the README does not appear to be an issue, I'm running the container with the following command:

```
docker run    --name ejabberd --hostname "xmpp.mydomain.com" \
              -p 5222:5222 \
              -v "$(pwd)/host.pem:/tmp/ssl/host.pem" -v "$(pwd)/host.pem:/tmp/ssl/xmpp_domain.pem" \
              --expose 5280 \
              -v ejabberd-conf:/opt/ejabberd/conf -v ejabberd-ssl:/opt/ejabberd/ssl -v ejabberd-db:/opt/ejabberd/database -v ejabberd-upload:/opt/ejabberd/upload \
              --restart always \
               rroemhild/ejabberd:latest
```
I don't see anything in the log indicating why the container is exiting. It looks to me like the `run.sh start` script is exiting 0 after one minute, possibly because the `ejabberdctl foreground` process returns, causing the `wait` to exit. When I run the container with a shell and manually run `/sbin/run start`, the script exits after one minute but ejabberd continues running.

**Comment by scallopedllama** [comment]
Think I'm on to something.

`run.sh` has `set -e` configured. It looks like the `ejabberdctl started` command is timing out. The `ejabberdctl` script gives it 30 x 2s or it returns 1.That being the last function call in the script, causes the script itself to exit 1 and that causes `run.sh` to fail, exiting 1.

**Comment by rroemhild** [comment]
Maybe an issue with the config or the mounted volumes. Can you post the log output?

**Comment by scallopedllama** [comment]
I think it might be failing because ejabberdctl can't connect to ejabberd's XMLRPC.

I had the XMLRPC ports disabled in the config but even with them turned back on it dies after one minute.

Here is my config file:

```yml
###
###               ejabberd configuration file
###
###

### The parameters used in this configuration file are explained in more detail
### in the ejabberd Installation and Operation Guide.
### Please consult the Guide in case of doubts, it is included with
### your copy of ejabberd, and is also available online at
### http://www.process-one.net/en/ejabberd/docs/

###   =======
###   LOGGING

loglevel: 4
log_rotate_size: 10485760
log_rotate_count: 0
log_rate_limit: 100

## watchdog_admins:
##   - "bob@example.com"

###   ================
###   SERVED HOSTNAMES

hosts:
  - "xmpp.mydomain.com"

##
## route_subdomains: Delegate subdomains to other XMPP servers.
## For example, if this ejabberd serves example.org and you want
## to allow communication with an XMPP server called im.example.org.
##
## route_subdomains: s2s

###   ===============
###   LISTENING PORTS

listen:
  -
    ## XMPP Connections from clients
    port: 5222
    module: ejabberd_c2s
    starttls_required: true
    protocol_options:
      - "no_sslv3"
      - "no_tlsv1"
    ## Note: set max_stanza_size to not-infinity if people are DOS'ing the server
    max_stanza_size: infinity
    shaper: c2s_shaper
    access: c2s
    ciphers: "HIGH:!aNULL:!3DES"

    ## NOTE: Do not enable the ejabberd_s2s_in module

  -
    port: 4560
    module: ejabberd_xmlrpc
    access_commands:
      configure:
        all: []

  -
    ## Admin Portal
    port: 5280
    module: ejabberd_http
    request_handlers: {}
    ## NOTE: "/admin" is reserved for the web_admin: true setting
    web_admin: true
    http_bind: true
    captcha: true
    ## NOTE: SSL is not enabled here as it is encrypted by the outside nginx-proxy
    


###   SERVER TO SERVER
###   If there is no listen for s2s configured, s2s does not do anything.
###   ================
s2s_use_starttls: required
s2s_certfile: "/opt/ejabberd/ssl/host.pem"
s2s_protocol_options:
  - "no_sslv3"
  - "no_tlsv1"
s2s_ciphers: "HIGH:!aNULL:!3DES"


###   ==============
###   AUTHENTICATION

auth_method:
  - ldap

auth_password_format: scram


## LDAP authentication

ldap_servers:
  - "0.0.0.0"
ldap_encrypt: none
ldap_tls_verify: false
ldap_tls_depth: 1
ldap_rootdn: "ROOTDN-HERE"
ldap_password: "PASSWORD"
ldap_deref_aliases: never
ldap_base: "LDAP_BASE"
ldap_uids:
  "uid": "%u"

###   ===============
###   TRAFFIC SHAPERS

shaper:
  normal: 1000
  fast: 50000
max_fsm_queue: 1000

###   ====================
###   ACCESS CONTROL LISTS

acl:
  admin:
    user:
      - "admin": "xmpp.mydomain.com"
  local:
    user_regexp: ""

###   ============
###   ACCESS RULES

access:
  ## Maximum number of simultaneous sessions allowed for a single user:
  max_user_sessions:
    all: 10
  ## Maximum number of offline messages that users can have:
  max_user_offline_messages:
    admin: 5000
    all: 5000
  ## This rule allows access only for local users:
  local:
    local: allow
  ## Only non-blocked users can use c2s connections:
  c2s:
    blocked: deny
    all: allow
  ## For C2S connections, all users except admins use the "normal" shaper
  c2s_shaper:
    admin: none
    all: normal
  ## All S2S connections use the "fast" shaper
  s2s_shaper:
    all: fast
  ## Only admins can send announcement messages:
  announce:
    admin: allow
  ## Only admins can use the configuration interface:
  configure:
    admin: allow
  ## Admins of this server are also admins of the MUC service:
  muc_admin:
    admin: allow
  ## Only accounts of the local ejabberd server can create rooms:
  muc_create:
    local: allow
    
  ## All users are allowed to use the MUC service:
  muc:
    all: allow
  ## Only accounts on the local ejabberd server can create Pubsub nodes:
  pubsub_createnode:
    local: allow
  ## In-band registration allows registration of any possible username.
  register:
    all: allow
    
  ## Only allow to register from localhost
  trusted_network:
    loopback: allow
  soft_upload_quota:
    all: 400 # MiB
  hard_upload_quota:
    all: 500 # MiB


language: "en"

###   =======
###   MODULES

modules:
  mod_adhoc: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state:
    queue_chat_states: true
    queue_presence: false
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  ## mod_echo: {}
  ## mod_irc: {}
  mod_http_bind: {}
  ## mod_http_fileserver:
  ##   docroot: "/var/www"
  ##   accesslog: "/var/log/ejabberd/access.log"
  mod_last: {}
  mod_mam:
    default: always
  mod_muc:
    host: "conference.@HOST@"
    access: muc
    access_create: muc_create
    access_persistent: muc_create
    access_admin: muc_admin
    history_size: 50
    default_room_options:
      persistent: true
  ## mod_muc_log: {}
  ## mod_multicast: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  ## mod_pres_counter:
  ##   count: 5
  ##   interval: 60
  mod_privacy: {}
  mod_private: {}
  ## mod_proxy65: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ## reduces resource comsumption, but XEP incompliant
    ignore_pep_from_offline: true
    ## XEP compliant, but increases resource comsumption
    ## ignore_pep_from_offline: false
    last_item_cache: false
    plugins:
      - "flat"
      - "hometree"
      - "pep" # pep requires mod_caps
  mod_push: {}
  mod_push_keepalive: {}
  mod_stream_mgmt: {}
  ## mod_register: {}
  mod_roster: {}
  mod_shared_roster: {}
  mod_stats: {}
  mod_time: {}
  mod_vcard: {}
  mod_vcard_ldap: {}
  
  ## mod_http_upload: {}
  ## mod_http_upload_quota: {}

###   ============
###   HOST CONFIG

host_config:
  "xmpp.mydomain.com":
    domain_certfile: "/opt/ejabberd/ssl/xmpp.mydomain.com.pem"

###   =====================
###   SESSION MANAGEMENT DB
sm_db_type: mnesia
```
