### ISSUE TITLE
Postgres insert error when install ejabberd register user with null value 

### ISSUE THREAD

**Issue by kevin71020** [rroemhild/docker-ejabberd#154]
I am configuring Ejabberd to use Postgres as backend. It seems that Ejabberd can not register new  users in  DB.
It has null value in colume “server_host” when ejabberd register user.

error.log 
```
ejabberd_1  | /opt/ejabberd/scripts/post/10_ejabberd_modules_update_specs.sh...
ejabberd_1  | /opt/ejabberd/scripts/post/11_ejabberd_install_modules.sh...
ejabberd_1  | /opt/ejabberd/scripts/post/20_ejabberd_register_users.sh...
ejabberd_1  | 19:09:56.479 [debug] Command 'register' execution allowed by rule 'console commands' (CallerInfo=#{caller_module => ejabberd_ctl})
ejabberd_1  | 19:09:56.479 [debug] Executing command ejabberd_admin:register with Args=[<<"admin">>,<<"mac.example.com">>,<<"a12345">>]
ejabberd_1  | 19:09:56.495 [error] SQL query 'Q73531467' at {ejabberd_auth_sql,179} failed: [{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"23502">>},{message,<<"null value in column \"server_host\" violates not-null constraint">>},{detail,<<"Failing row contains (admin, null, b1uxcdq, , , 0, 2017-12-22 11:09:56.493201).">>},{115,<<"public">>},{116,<<"users">>},{99,<<"server_host">>},{file,<<"execMain.c">>},{line,1731},{routine,<<"ExecConstraints">>}]
ejabberd_1  | Error: conflict

```

docker-compose.yml 

```
version: "2"
  ejabberd:
    image: rroemhild/ejabberd
    ports:
      - 5222:5222
      - 5269:5269
      - 5280:5280
    environment:
      - ERLANG_NODE=ejabberd
      - XMPP_DOMAIN=mac.exmaple.com
      - EJABBERD_ADMINS=admin@mac.exmaple.com
      - EJABBERD_USERS=admin@mac.exmaple.com:a1234 kt@mac.exmaple.com:a1234
      - TZ=Asia/Taipei
      # Modules
      - EJABBERD_SKIP_MODULES_UPDATE=true
      # Logging
      - EJABBERD_LOGLEVEL=5
      # PostgreSQL Everything 
      - EJABBERD_AUTH_METHOD=sql
      - EJABBERD_CONFIGURE_ODBC=true
      - EJABBERD_ODBC_TYPE=pgsql
      - EJABBERD_ODBC_SERVER=mac.exmaple.com
      - EJABBERD_ODBC_DATABASE=ejabberd
      - EJABBERD_ODBC_USERNAME=ejabberd
      - EJABBERD_ODBC_PASSWORD=a12345
    volumes:
        - ~/Certificates/ejabberd/ssl:/opt/ejabberd/ssl
        - ~/docker/ejabberd/log:/usr/local/var/log/ejabberd/
        - ~/docker/ejabberd/backup:/opt/ejabberd/backup
```
