### ISSUE TITLE
Ejabberd shared roaster group with members @all@

### ISSUE THREAD

**Issue by bp91** [rroemhild/docker-ejabberd#178]
Hi, I've tried to create a container docker with a docker-compose file with the following configuration:

```
ejabberd:
    build: ejabberd
    container_name: ejabberd
    volumes:
      - ./ejabberd/conf/ejabberd.yml:/opt/ejabberd/conf/ejabberd.yml
      - ./ejabberd/database/:/opt/ejabberd/database/
      - ./ejabberd/certs/:/opt/ejabberd/certs/
    expose:
      - "4369"
      - "5222"
      - "5269"
      - "5280"
      - "7070"
      - "9090"
    environment:
      - ERLANG_NODE=ejabberd@localhost
      - XMPP_DOMAIN=test.biz
      - EJABBERD_ADMINS=admin@test.biz
      - EJABBERD_GROUPS=test@test.biz
      - EJABBERD_GROUP_MEMBERS=@all@:test@test.biz
    networks:
      default:
        ipv4_address: 10.5.0.8
```

So I tried to create a shared roaster group with members **@all@**, but it not working. The group was created correctly, but with no members.
Is it possible to do this?
