### ISSUE TITLE
SSL/TLS  problem

### ISSUE THREAD

**Issue by dirkmoors** [rroemhild/docker-ejabberd#72]
Hi @rroemhild 

While testing docker-ejabberd with a certificate, I noticed that I was unable to connect from e.g. https://conversejs.org/. 

My certificate is in:
```
/opt/ejabberd/ssl/my-xmpp-domain.com.pem
```
Ejabberd picks it up, since it only generates the host.pem.

When I try to connect (e.g. from converse.js), Ejabberd throws the following error:
```
SSL_do_handshake failed: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
```
Having an older ejabberd.yml file lying around, I compared that one with the current template in this repo, and I noticed the following:

The template in this repo:
```yml
...
listen:
  -
    port: 5222
    module: ejabberd_c2s
    {%- if env['EJABBERD_STARTTLS'] == "true" %}
    starttls_required: true
    {% endif %}
    protocol_options:
      - "no_sslv3"
      - "no_tlsv1"
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
...
```

My old config:
```yml
...
listen:
  -
    port: 5222
    module: ejabberd_c2s
    starttls: true
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
...
```
Assuming that EJABBERD_STARTTLS == "true", the main difference is the section "protocol_options". The question is; "do we want that as a default"? And if we do, how can we make the image compatible with something like converse.js? 

p.s. I've used converse.js as an easy test, but the same failure also occured on an Android and iOS library I'm working on.
