### ISSUE TITLE
Ejabberd doesn't advertise stream features

### ISSUE THREAD

**Issue by janekolszak** [rroemhild/docker-ejabberd#95]
Hi,
I started the container for localhost development with docker-compose and XMPP clients can't connect.

The problem seems to be that there's no <mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'> in the features stream.

Features:
```
<stream:features xmlns:stream='http://etherx.jabber.org/streams'>
    <c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.process-one.net/en/ejabberd/' ver='1h0AkH4ZFdRE+5QKmkJjNRZy5yQ='/>
    <starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'><required/></starttls>
</stream:features>

```

docker-compose.yml:
```
ejabberd:
  image: rroemhild/ejabberd
  ports:
    - 5222:5222
    - 5269:5269
    - 5280:5280
  environment:
    - ERLANG_NODE=ejabberd
    - XMPP_DOMAIN=localhost
    - EJABBERD_ADMINS=admin@localhost
    - EJABBERD_USERS=admin@localhost:password4321
    - EJABBERD_AUTH_METHOD=internal
```

Thanks!
